local map = function(mode, lhs, rhs, opts)
	local options = { noremap = true, silent = true }
	if opts then
		options = vim.tbl_extend("force", options, opts)
	end
	vim.keymap.set(mode, lhs, rhs, options)
end

map("n", "<Leader>e", ":NvimTreeToggle<CR>", { desc = "Toggle Explorer" })
map("n", "<Leader>n", ":tabnew<CR>", { desc = "New Buffer" })
map("n", "<Leader>o", ":NvimTreeFocus<CR>", { desc = "Focus Explorer" })
map("n", "<Leader>z", ":ZenMode<CR>", { desc = "Toggle ZenMode" })
map("n", "<Leader>x", ":TroubleToggle<CR>", { desc = "Toggle Trouble Menu" })
map("n", "<A-,>", ":BufferPrevious<CR>")
map("n", "<A-.>", ":BufferNext<CR>")
map("n", "<A-<>", ":BufferMovePrevious<CR>")
map("n", "<A->>", ":BufferMoveNext<CR>")
map("n", "<A-1>", ":BufferGoto 1<CR>")
map("n", "<A-2>", ":BufferGoto 2<CR>")
map("n", "<A-3>", ":BufferGoto 3<CR>")
map("n", "<A-4>", ":BufferGoto 4<CR>")
map("n", "<A-5>", ":BufferGoto 5<CR>")
map("n", "<A-6>", ":BufferGoto 6<CR>")
map("n", "<A-7>", ":BufferGoto 7<CR>")
map("n", "<A-8>", ":BufferGoto 8<CR>")
map("n", "<A-9>", ":BufferGoto 9<CR>")
map("n", "<A-0>", ":BufferLast<CR>")
map("n", "<A-p>", ":BufferPin<CR>")
map("n", "<A-c>", ":BufferClose<CR>")
map("n", "<C-p>", ":BufferPick<CR>")
map("n", "<Leader>bb", ":BufferOrderByBufferNumber<CR>", { desc = "Order Buffers by Number" })
map("n", "<Leader>bd", ":BufferOrderByDirectory<CR>", { desc = "Order Buffers by Directory" })
map("n", "<Leader>bl", ":BufferOrderByLanguage<CR>", { desc = "Order Buffers by Language" })
map("n", "<Leader>bw", ":BufferOrderByWindowNumber<CR>", { desc = "Order Buffers by Window Number" })
map("n", "<C-s>", ":w<CR>")

require("which-key").register()
